// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// window_regression_cpp
List window_regression_cpp(const List& Ylist, const List& Xlist, int radius, int min_cells, double min_variance, int threads);
RcppExport SEXP _topocast_window_regression_cpp(SEXP YlistSEXP, SEXP XlistSEXP, SEXP radiusSEXP, SEXP min_cellsSEXP, SEXP min_varianceSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type Ylist(YlistSEXP);
    Rcpp::traits::input_parameter< const List& >::type Xlist(XlistSEXP);
    Rcpp::traits::input_parameter< int >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< int >::type min_cells(min_cellsSEXP);
    Rcpp::traits::input_parameter< double >::type min_variance(min_varianceSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(window_regression_cpp(Ylist, Xlist, radius, min_cells, min_variance, threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_topocast_window_regression_cpp", (DL_FUNC) &_topocast_window_regression_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_topocast(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
