# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

window_regression_cpp <- function(y, Xlist, radius, min_cells, min_variance) {
    .Call(`_topocast_window_regression_cpp`, y, Xlist, radius, min_cells, min_variance)
}

